function Ypred = wtTest(X,Y,indsTrain,indsTest,method,model,XDataCluster)

Ypred = downWT(X,Y,...
             indsTrain,indsTest,...
             model.clustering,...
             'method',method.properties.InferenceMethod,'model',model);
